#!/bin/bash

color_print() {
    Font_Black="\033[30m"
    Font_Red="\033[31m"
    Font_Green="\033[32m"
    Font_Yellow="\033[33m"
    Font_Blue="\033[34m"
    Font_Purple="\033[35m"
    Font_SkyBlue="\033[36m"
    Font_White="\033[37m"
    Font_BrightBlack="\033[90m"
    Font_BrightRed="\033[91m"
    Font_BrightGreen="\033[92m"
    Font_BrightYellow="\033[93m"
    Font_BrightBlue="\033[94m"
    Font_BrightPurple="\033[95m"
    Font_BrightSkyBlue="\033[96m"
    Font_BrightWhite="\033[97m"
    Font_Orange="\033[38;5;208m"
    Font_Suffix="\033[0m"
}
color_print

function showGoodbye() {
   
    echo -e ''
    echo -e "${Font_Green}┏---------------------------------------------------┓${Font_Suffix}"
    echo -e "  radonet.co.uk 港日云主机\n\n  日本静态/动态住宅 IP 可按需求定制\n   \n  Nuro光 (Sony) /Ucom光 (Arteria) / Softbank光\n  香港大宽带国际路线\n  日本大带宽直连 / 国际路线\n  官网: ${Font_BrightBlue}https://radonet.co.uk${Font_Suffix}\n  TG 频道：${Font_BrightBlue}https://t.me/radonetlog${Font_Suffix}"
    echo -e ""
    echo -e "${Font_Green}┗---------------------------------------------------┛${Font_Suffix}"
    echo -e ''
    echo -e ''

}
showGoodbye
