#!/bin/bash

color_print() {
    Font_Black="\033[30m"
    Font_Red="\033[31m"
    Font_Green="\033[32m"
    Font_Yellow="\033[33m"
    Font_Blue="\033[34m"
    Font_Purple="\033[35m"
    Font_SkyBlue="\033[36m"
    Font_White="\033[37m"
    Font_BrightBlack="\033[90m"
    Font_BrightRed="\033[91m"
    Font_BrightGreen="\033[92m"
    Font_BrightYellow="\033[93m"
    Font_BrightBlue="\033[94m"
    Font_BrightPurple="\033[95m"
    Font_BrightSkyBlue="\033[96m"
    Font_BrightWhite="\033[97m"
    Font_Orange="\033[38;5;208m"
    Font_Suffix="\033[0m"
}
color_print

function showGoodbye() {
   
    echo -e ''
    echo -e "${Font_Green}┏---------------------------------------------------┓\n${Font_Suffix}"
    echo -e "  韩国家宽DNS解锁\n  解锁本地流媒体及游戏\n  支持指定ISP例如KT,LG,SK等\n  无限流量费用仅需15USD/月/VPS\n  购买或试用请联系${Font_BrightBlue}https://t.me/czgno${Font_Suffix}"
    echo -e ""
    echo -e "${Font_Green}┗---------------------------------------------------┛\n${Font_Suffix}"
    echo -e ''
    echo -e ''

}
showGoodbye
